name: konjugator
description: A German verb conjugation app.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0 < 3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # third party
  flutter_launcher_icons: ^0.9.0

flutter:
  uses-material-design: true

  # fonts used in the app
  fonts:
    - family: Aleo
      fonts:
        - asset: assets/fonts/Aleo-Regular.otf
        - asset: assets/fonts/Aleo-Italic.otf
          style: italic
        - asset: assets/fonts/Aleo-Bold.otf
          weight: 700
        - asset: assets/fonts/Aleo-Light.otf
          weight: 100

# settings for flutter_launcher_icons package
flutter_icons:
  android: "ic_launcher" 
  ios: true
  image_path: "assets_dev/app_icon/app_icon.png"
  adaptive_icon_background: "#FF9BA8BA"
  adaptive_icon_foreground: "assets_dev/app_icon/android.png"